//
// Created by pepef on 22.07.2022.
//

#ifndef BEDROCKPOWDER_CONSTANTS_H
#define BEDROCKPOWDER_CONSTANTS_H

#define BEDROCKPOWDER_IS_DEV true
#define BEDROCKPOWDER_CORE_NAME "BedrockPowder"
#define BEDROCKPOWDER_VERSION "1.0.2-alpha"

#endif //BEDROCKPOWDER_CONSTANTS_H
